/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sofia' at '18/11/2018, 20:54' with Gradle 2.10
 *
 * @author sofia, @date 18/11/2018, 20:54
 */
package com.where_next;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WhereNextApplication {

    public static void main(String[] args) {
        SpringApplication.run(WhereNextApplication.class, args);
    }

}
