package com.where_next.controllers;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sofia' at '18/11/2018, 20:54' with Gradle 2.10
 *
 * @author sofia, @date 18/11/2018, 20:54
 */

import org.junit.jupiter.api.Test;

public class WelcomeControllerTest {

    @Test
    public void shouldSayHelloToTheWorld()  {
    }
}

